# Generated by Django 4.0.4 on 2022-09-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
