# Generated by Django 4.0.4 on 2022-09-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0005_user2_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
